// This file will be generated by Supabase CLI later.
// For now, keep a lightweight schema with the functions we call so RPC is typed.

type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      accounts: {
        Row: {
          id: string
          user_id: string
          name: string
          plan_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          plan_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          plan_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Functions: {
      can_create_project: {
        Args: { account_uuid: string }
        Returns: boolean
      }
      can_create_form: {
        Args: { project_uuid: string; account_uuid?: string }
        Returns: boolean
      }
      can_accept_response: {
        Args: { form_uuid: string }
        Returns: boolean
      }
      get_project_usage_summary: {
        Args: { account_uuid: string }
        Returns: Json[]
      }
      get_account_responses_count: {
        Args: { account_uuid: string; start_date?: string }
        Returns: number
      }
      increment_qr_scan: {
        Args: { qr_code_uuid: string }
        Returns: number | null
      }
      reorder_questions: {
        Args: { form_uuid: string; question_ids: string[]; order_indexes: number[] }
        Returns: null
      }
      [key: string]: {
        Args: Record<string, any>
        Returns: any
      }
    }
    Views: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
